services:
  - type: web
    name: laptop-price-predictor
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: streamlit run app.py
    pythonVersion: 3.8.0
